"""initial migration

Revision ID: 161387674862
Revises: 
Create Date: 2019-03-25 19:10:41.813215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161387674862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('novel_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'novel_name')
    # ### end Alembic commands ###
