"""change

Revision ID: d89569aac33e
Revises: 
Create Date: 2018-02-12 20:53:33.536257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89569aac33e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('diy_avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'diy_avatar')
    op.drop_column('posts', 'tag')
    # ### end Alembic commands ###
